# Site settings
title: 'ronfe'  # Your Title
tagline: 'Discovery is the ability to be puzzled by simple things '  # A brief tagline for your site
sidebar_image: /images/cover.jpg


# Build settings
encoding: UTF-8
markdown: kramdown
#markdown: redcarpet
#highlighter: pygments
highlighter: true
baseurl: # the subpath of your site, e.g. /blog/
